[package]
name = "math_solve"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos = { version = "0.7", features = ["csr"] }
console_error_panic_hook = "0.1"
user_algebra = { git = "https://github.com/MarcoAdami/user_algebra.git" }
gloo = "0.12.0"


[package.metadata.leptos]
site-root = "target/site"
site-pkg-dir = "pkg"
site-addr = "127.0.0.1:8080"